"""Generate a report strictly from a completed stage-four experiment."""
import json,statistics,sys
from pathlib import Path
run=Path(sys.argv[1]);rows=json.loads((run/'metrics.json').read_text());env=json.loads((run/'environment.json').read_text())
assert len(rows)==6, 'Incomplete experiment: expected both modes and all three cases'
def avg(values):return statistics.mean(values) if values else 0
lines=['# 阶段四压测报告','', '阶段：入口限流、接口防刷、请求幂等。比较同一阶段四 JAR 的 stage3 无保护模式和 stage4 保护模式。','',f"测试环境：{env['platform']}，{env['logical_cpus']} 逻辑核、{env['memory_bytes']/1024**3:.1f} GiB；Java 21、Spring Boot 3.3.5、MySQL {env['mysql_version']}、Redis {env['redis_version']}、RabbitMQ {env['rabbitmq_version']}。JMeter 5.6.3、应用和 MySQL 同机；Redis/RabbitMQ 位于 WSL。",'',f"测试环境参数：连接池 {env['pool_size']}、消费者 {env['consumers']}、prefetch {env['prefetch']}、ramp {env['ramp_seconds']} 秒、仅一轮。全局写入 rate={env['write_global_rate']}/s、capacity={env['write_global_capacity']}；因压测同源 IP，临时提升 IP 配额至 {env['write_ip_rate_override']}/s、capacity={env['write_ip_capacity_override']}；实际应用默认 IP 配额为 50/s、capacity=20。",'',f"并发用户/请求数量：每模式预热 10 并发 200 次；正常流量 10 并发 500 次、每线程额外等待 100ms；过载 100 并发 {env['requests']} 次、无额外等待。每请求 userId 和 UUID 键不同。两个模式顺序执行。",'',f"原始证据：`{run.as_posix()}`。JAR SHA256：`{env['jar_sha256']}`。包含原始 JTL、JMeter/application 日志、CPU/MySQL/队列时序、脚本和测试计划快照。",'','## 请求与业务结果','', '| 模式/场景 | 并发 | 请求 | 总 HTTP QPS | 受理 QPS | 平均 ms | 最大 ms | 受理平均 ms | 202 成功受理 | 429 拒绝 | 其他失败 | 最终订单 | 剩余库存 |','|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|']
for r in rows:
 c=r['codes'];other=sum(v for k,v in c.items() if k not in ['202','429']);accepted_avg='未采集' if r['accepted_avg_ms'] is None else f"{r['accepted_avg_ms']:.2f}"
 lines.append(f"| {r['mode']}/{r['case']} | {r['users']} | {r['requests']} | {r['http_qps']:.2f} | {r['accepted_qps']:.2f} | {r['avg_ms']:.2f} | {r['max_ms']} | {accepted_avg} | {c.get('202',0)} | {c.get('429',0)} | {other} | {r['orders']} | {r['remaining_stock']} |")
lines+=['','成功请求指 HTTP 202 被 MQ 接收；成交必须以最终订单为准。429 在 JMeter 中计入失败请求，但这里单独列为预期主动拒绝；总非成功请求 = 429 + 其他失败。两组初始库存都等于请求量，没有人为用售罄掩盖限流效果。正常组预期不拒绝，过载组预期出现 429。','','总 HTTP QPS 包含快速返回的 429；受理 QPS = 202 数量 / 请求窗口。令牌桶允许最初的突发，短窗口受理 QPS 可超过 rate，须检查 capacity + rate × 窗口时长。HTTP 响应延迟不是最终订单端到端延迟。本轮未记录逐单最终延迟。','','## 数据库、队列和资源','', '| 模式/场景 | MySQL Questions 增量 | 行锁等待次数/ms | MySQL 平均 CPU% | 应用平均 CPU% | 系统平均/峰值 CPU% | Redis平均CPU% | 观察队列峰值 | JMeter结束后核验等待秒 | 完成 QPS 下界 |','|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|']
for r in rows:
 samples=r['samples'];system=[s['system_cpu'] for s in samples];mysql=[v for s in samples for k,v in s.items() if k.startswith('mysql-') and k.endswith('_cpu')];a=r['status_after'];b=r['status_before'];peak=max(s['queue_ready']+s['queue_unacked'] for s in samples)
 lines.append(f"| {r['mode']}/{r['case']} | {a['Questions']-b['Questions']} | {a['Innodb_row_lock_waits']-b['Innodb_row_lock_waits']}/{a['Innodb_row_lock_time']-b['Innodb_row_lock_time']} | {avg(mysql):.2f} | {avg([s.get('app_cpu',0) for s in samples]):.2f} | {avg(system):.2f}/{max(system):.2f} | {r['redis_cpu_seconds']/r['monitor_seconds']/env['logical_cpus']*100:.2f} | {peak} | {r['drain_wait_after_jmeter_seconds']:.2f} | {r['verified_completion_qps_lower_bound']:.2f} |")
lines+=['','CPU 为整机归一化百分比；进程 CPU 除以逻辑核数。MySQL Questions 是全局增量，包含监控查询和其他同机活动；不能等同于业务写入次数。采样含 JMeter 启停及队列耗尽阶段。RabbitMQ 进程 CPU 未单独采集。队列管理 API 有约 5 秒统计延迟，观察峰值只是下界。完成 QPS 下界的时间窗口延伸至脚本确认全部订单完成，含 JMeter 退出和轮询延迟，不是精确消费者吞吐。','','## 限流前后比较','']
old=next(r for r in rows if r['mode']=='unprotected' and r['case']=='overload');new=next(r for r in rows if r['mode']=='protected' and r['case']=='overload')
old_peak=max(s['queue_ready']+s['queue_unacked'] for s in old['samples']);new_peak=max(s['queue_ready']+s['queue_unacked'] for s in new['samples'])
lines += [f"- 同为 {old['requests']} 次过载请求：无保护受理 {old['codes'].get('202',0)}，有保护受理 {new['codes'].get('202',0)}、主动拒绝 {new['codes'].get('429',0)}。",f"- 观察队列峰值：{old_peak} → {new_peak}；JMeter 结束后到全部订单/pending 核验完成等待：{old['drain_wait_after_jmeter_seconds']:.2f}s → {new['drain_wait_after_jmeter_seconds']:.2f}s。",f"- 本轮令牌桶受理界限：受理 {new['codes'].get('202',0)} ≤ 100 + 200 × ({new['seconds']:.3f}s + 0.1s测量余量)。",'- 每个案例均验证最终订单数等于受理数、剩余库存 + 订单 = 初始库存、pending=0。正常流量组未出现限流拒绝。','', '## 幂等和接口保护验证','', '独立真实集成测试验证 100 次相同业务请求只发布一次消息、最终只建一单；相同键换商品冲突；不同用户可使用相同键；ticket 过期后仍可返回原数据库订单；发布超时和重试不再次扣库存/发消息；缺失键返回 400；全局/用户/IP 查询桶拒绝；伪造 X-Forwarded-For 无法绕过来源限制；令牌并发扣减和补充正确；损坏限流状态停止放行。42 项全量测试通过，详见 stage4-test-results.txt。', '', '## 当前问题与结论边界','', '本轮实验验证入口主动拒绝、减少进入 MQ 的请求和最终库存一致性。限流是在过载时牺牲部分请求受理率保护下游，不是数据库写入能力提升。正常请求增加 Redis 检查可能变慢；429 很快返回可能抬高总 QPS。', '', '本实验只有一轮、时间短、JMeter 闭环发送且与服务同机；429 更快返回会改变后续请求发送节奏，两组不是严格相同的开环到达率。不能据此证明长期稳定性、最大容量或生产 SLA；还需要长时间持续超载、外部压测机和多轮重复。userId 尚未认证、永久幂等 marker 需要归档、Redis/MQ 无跨系统事务，均未在本阶段消除。']
Path('docs/stage4-report.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')
print('Generated docs/stage4-report.md')
